// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {PoseidonT3} from "../hash/PoseidonT3.sol";

/// @title IncrementalMerkleTree
/// @notice Append-only incremental Merkle tree of depth 32 over BN254 Fr, using
///         Poseidon-128 (Bn254PoseidonMerkleSpec) as the layer hash.
///
/// The "filled subtrees" (frontier) technique is used: only 32 storage slots are
/// needed.  Each `insert` call performs exactly 32 Poseidon hash calls (≈16k EVM gas)
/// and returns the new Merkle root.
///
/// Layer hash: `compress(level, left, right) = PoseidonT3.hash3(level, left, right)`
/// This matches the Rust circuit precisely so that a Merkle-path proof generated
/// off-chain will verify against the on-chain root.
///
/// Test vectors (from `dump_poseidon_constants`, big-endian):
///   Empty tree root (32 levels, no leaves) =
///     0x2cbe967b6ba6d0faa4e84ea623d11dc747854fd32ecaa48c721635243d37d79f
///   After insert(42) =
///     0x261dd3eef09f9ac35c2e82979754b65461b0f080913bf780964fb30281c0c77e
///   After insert(1) then insert(2) =
///     0x2acffa6ebc8752bc99668a083a482d3d0cec6ed4af1d191ac5dc727616593140
library IncrementalMerkleTree {
    uint256 internal constant DEPTH = 32;

    // ── Empty subtree hashes ──────────────────────────────────────────────────
    // EMPTY[l] = compress(l-1, EMPTY[l-1], EMPTY[l-1])
    // EMPTY[0] = 0  (empty leaf)
    // Generated by `vendor/orchard-bn254/src/bin/dump_poseidon_constants.rs`

    function _empty(uint256 l) internal pure returns (uint256) {
        if (l == 0)  return 0;
        if (l == 1)  return 0x0ce694d99c2e5df8479226fcf9fd0af13d8a79df89edbf7cf14c298e3a979117;
        if (l == 2)  return 0x0d3690e5d11843c72f613dd6b431843c262c2e0587c4f8a4e1512ba1409c62d5;
        if (l == 3)  return 0x24886e267b33c365d7c0668663a8cd70ee4f786bf375b821f80b1195784f2233;
        if (l == 4)  return 0x1097e0ddd47dbc70a288d14b732643f4cc7be442b60862a128f80c9cee9a1636;
        if (l == 5)  return 0x06eae6b1dedbf2d1aa031ae33bd9823316a8532b1af5e94eb433d32733c11866;
        if (l == 6)  return 0x18e08ef4963c5c3e36082add961e87489434e918b8293fe5f2b376d7e2e47116;
        if (l == 7)  return 0x26c229eec803e1fff07b4f26d4e60d83e53e6d83ca96882ed4fd127e0c5b6a70;
        if (l == 8)  return 0x0037b663852aad50fd695fc04c0a3dd4d8634b9da9dbf5fe7b2f320dd41c137d;
        if (l == 9)  return 0x10ed88d9112076444ea85c955acbace6362520a06c780509cebeacace0a0ac11;
        if (l == 10) return 0x2a6dc053f2a962af1faa7d77d2c0b0ec360e1efec9261c78d5b3742ba29b0e0e;
        if (l == 11) return 0x1023157e8f24c7e747da4fe36e1d22e2521bc125dbd2bb9a4bda1ababd6ab62c;
        if (l == 12) return 0x165099d1550c09433c8b6d42c34ddecd7fd20cbe420aa32a3a40082fbe2448f1;
        if (l == 13) return 0x08e357ad3ebdea2a60728d75b5a9c80b78d6fd92890c3e760b4a5ca0c7d9d128;
        if (l == 14) return 0x0cf58d9d11f4f8fbbd973761534970810e977a575e8ce1d0a4549ae9bba8f4a5;
        if (l == 15) return 0x244b4053eebb5bf226b9106d265afc2f7c72ae872f55e6f38d156276524dfd37;
        if (l == 16) return 0x2f3c2f7407b69915e2227ff3a484b380b5c14b492c49679e6a9e69ae57cabd82;
        if (l == 17) return 0x0209644d621d1c92545a93cc1be8ff28f33d83a156a28fdf8bde20743e6e0e64;
        if (l == 18) return 0x01ceb2ee3b0a0038d2bd3608f23cf441e04ac0e8f382def40d4ee94a78e1cb9d;
        if (l == 19) return 0x06465c789f76393377f8448c2fe940b2e6c13d044f631e04c54ffc01d07b81ad;
        if (l == 20) return 0x0769d99c5cc508f8991083f9c8d65fb6b40d587a7d535b5469f2786c03cb55f0;
        if (l == 21) return 0x15adcb0ace2c07cb8ae9e54b4dafc0fb815e4085696903d20dd1870d3bc7a39a;
        if (l == 22) return 0x210693cf748f65b37c3a8824858b5e0f30576d7c836e9a7772016f86d816eb7d;
        if (l == 23) return 0x16f4faade295d8bf738cb047bf6ec2fdd08af097c21831355f94d65bc37b5d9b;
        if (l == 24) return 0x0a24319fe2b716da09eaeae217418b55cc63b296072063dbab9b5094b8003101;
        if (l == 25) return 0x1a98528afa77bf0032248acdd5342a64e8bc07529e115a4ad5b1dd9db2c95593;
        if (l == 26) return 0x0ba3a3d52ba05b1da038bf9fd436b4f0a6decc223f28ebab8867df3c6a8c98e6;
        if (l == 27) return 0x164cd35257fa7a52a86d5d0920315af21af72ce9a4893bbdbae0404e97d16644;
        if (l == 28) return 0x16c1b6647d3a5fb44b8f056ce0cf7c47027a9a78e9a157456edd769b68fa88c7;
        if (l == 29) return 0x1301d47b1b11f60cf14195e28ced0dd53225308a09abab077acb07f7d2f1f21e;
        if (l == 30) return 0x243db99ae9b29b1812a214bc34260a79e568d0045cba4d86c534dd86b7050e54;
        if (l == 31) return 0x06100d4585627f0ee68fe2593ee4367255c497995d133addc8a6427273100659;
        // l == 32  (empty root)
        return 0x2cbe967b6ba6d0faa4e84ea623d11dc747854fd32ecaa48c721635243d37d79f;
    }

    // ── Tree state ────────────────────────────────────────────────────────────

    /// @notice On-chain tree state (stored in the calling contract).
    /// @dev `filled[l]` = the hash of the last complete left subtree at depth l
    ///      that is waiting for its right sibling.
    struct State {
        uint256[32] filled;   // filled[l]: left sibling at level l
        uint256     nextIndex; // number of leaves inserted
        bytes32     root;      // current Merkle root (BN254 Fr as bytes32)
    }

    // ── Public API ────────────────────────────────────────────────────────────

    /// @notice Initialise a new empty tree; must be called once before insert.
    function init(State storage self) internal {
        self.nextIndex = 0;
        self.root = bytes32(_empty(DEPTH)); // empty tree root
    }

    /// @notice Insert a leaf and return the new Merkle root.
    /// @param  leaf  BN254 Fr value (e.g. commitment x-coordinate as uint256).
    function insert(State storage self, uint256 leaf)
        internal
        returns (bytes32 newRoot)
    {
        uint256 idx = self.nextIndex;
        require(idx < (1 << DEPTH), "IMT: tree full");
        self.nextIndex = idx + 1;

        // Walk from leaf level to root, maintaining the frontier.
        uint256 node = leaf;
        for (uint256 l = 0; l < DEPTH; l++) {
            if ((idx >> l) & 1 == 0) {
                // node is a LEFT child: store it and continue upward with an empty right sibling.
                self.filled[l] = node;
                node = PoseidonT3.hash3(l, node, _empty(l));
            } else {
                // node is a RIGHT child: combine with the stored left sibling.
                node = PoseidonT3.hash3(l, self.filled[l], node);
            }
        }

        newRoot = bytes32(node);
        self.root = newRoot;
    }
}
